bflow_app/bflow_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bflow_web.urls')),
]

bflow_app/bflow_web/urls.py
from django.urls import path
from . import views

app_name = "bflow_web"

urlpatterns = [
    path('sell/list/', views.sell_list, name='sell_list'),
    path('sell/create/', views.sell_create, name='sell_create'),
    path('calculate/list/', views.calculate_list, name='calculate_list'),
    path('calculate/create/', views.calculate_create, name='calculate_create'),
]

bflow_app/bflow_web/models.py
from django.db import models

# Create your models here.


class Calculate(models.Model):
    product_order_number = models.CharField(unique=True, max_length=50, blank=True, null=True)
    order_number = models.CharField(max_length=50, blank=True, null=True)
    channel_order_number = models.CharField(max_length=50, blank=True, null=True)
    order_state = models.CharField(max_length=50, blank=True, null=True)
    delivery_complete_at = models.DateField(blank=True, null=True)
    provide_name = models.CharField(max_length=50, blank=True, null=True)
    channel = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    order_amount = models.IntegerField(blank=True, null=True)
    fees = models.FloatField(blank=True, null=True)
    calculate = models.IntegerField(blank=True, null=True)
    channel_calculate = models.IntegerField(blank=True, null=True)
    complete_at = models.DateField(blank=True, null=True)
    matching_at = models.DateField(blank=True, null=True)
    week = models.IntegerField(blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    margin = models.IntegerField(blank=True, null=True)


           

    def __str__(self):
        return self.product_order_number


class Sell(models.Model):
    product_order_number = models.CharField(unique=True, max_length=50, blank=True, null=True)
    order_number = models.CharField(max_length=50, blank=True, null=True)
    payment_at = models.DateField(blank=True, null=True)
    order_state = models.CharField(max_length=50, blank=True, null=True)
    claim = models.CharField(max_length=50, blank=True, null=True)
    provide_name = models.CharField(max_length=50, blank=True, null=True)
    product_name = models.CharField(max_length=255, blank=True, null=True)
    product_option = models.CharField(max_length=255, blank=True, null=True)
    channel = models.CharField(max_length=50, blank=True, null=True)
    product_number = models.CharField(max_length=50, blank=True, null=True)
    product_amount = models.IntegerField(blank=True, null=True)
    option_amount = models.IntegerField(blank=True, null=True)
    seller_discount = models.IntegerField(blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    total_amount = models.IntegerField(blank=True, null=True)
    delivery_at = models.DateField(blank=True, null=True)
    delivery_complete = models.DateField(blank=True, null=True)
    order_complete_at = models.DateField(blank=True, null=True)
    auto_complete_at = models.DateField(blank=True, null=True)
    category_number = models.CharField(max_length=50, blank=True, null=True)
    buyer_email = models.CharField(max_length=50, blank=True, null=True)
    buyer_gender = models.CharField(max_length=50, blank=True, null=True)
    buyer_age = models.CharField(max_length=50, blank=True, null=True)
    crawler = models.CharField(max_length=50, blank=True, null=True)
    calculate = models.IntegerField(blank=True, null=True)
    calculate_channel = models.IntegerField(blank=True, null=True)
    margin = models.IntegerField(blank=True, null=True)
    profit = models.FloatField(blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    week = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.product_order_number


class Sellstatistics(models.Model):
    date = models.DateField(unique=True, blank=True, null=True)
    week = models.IntegerField(blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    brich_total_amount = models.IntegerField(blank=True, null=True)
    brich_qty = models.IntegerField(blank=True, null=True)
    brich_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    brich_margin = models.IntegerField(blank=True, null=True)
    brich_profit = models.FloatField(blank=True, null=True)
    gmarket_total_amount = models.IntegerField(blank=True, null=True)
    gmarket_qty = models.IntegerField(blank=True, null=True)
    gmarket_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    gmarket_margin = models.IntegerField(blank=True, null=True)
    gmarket_profit = models.FloatField(blank=True, null=True)
    auction_total_amount = models.IntegerField(blank=True, null=True)
    auction_qty = models.IntegerField(blank=True, null=True)
    auction_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    auction_margin = models.IntegerField(blank=True, null=True)
    auction_profit = models.FloatField(blank=True, null=True)
    st_total_amount = models.IntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    st_qty = models.IntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    st_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase. Field renamed because it wasn't a valid Python identifier.
    st_margin = models.IntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    st_profit = models.FloatField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    wemakeprice_total_amount = models.IntegerField(blank=True, null=True)
    wemakeprice_qty = models.IntegerField(blank=True, null=True)
    wemakeprice_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    wemakeprice_margin = models.IntegerField(blank=True, null=True)
    wemakeprice_profit = models.FloatField(blank=True, null=True)
    interpark_total_amount = models.IntegerField(blank=True, null=True)
    interpark_qty = models.IntegerField(blank=True, null=True)
    interpark_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    interpark_margin = models.IntegerField(blank=True, null=True)
    interpark_profit = models.FloatField(blank=True, null=True)
    coupang_total_amount = models.IntegerField(blank=True, null=True)
    coupang_qty = models.IntegerField(blank=True, null=True)
    coupang_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    coupang_margin = models.IntegerField(blank=True, null=True)
    coupang_profit = models.FloatField(blank=True, null=True)
    ssg_total_amount = models.IntegerField(blank=True, null=True)
    ssg_qty = models.IntegerField(blank=True, null=True)
    ssg_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    ssg_margin = models.IntegerField(blank=True, null=True)
    ssg_profit = models.FloatField(blank=True, null=True)
    g9_total_amount = models.IntegerField(blank=True, null=True)
    g9_qty = models.IntegerField(blank=True, null=True)
    g9_ct = models.IntegerField(blank=True, null=True)  # Field name made lowercase.
    g9_margin = models.IntegerField(blank=True, null=True)
    g9_profit = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.date

bflow_app/bflow_web/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Sum, F, Case, When, Q
from .models import Sell, Calculate
import openpyxl
import datetime


def replacedate(text):
    if text is None:
        return None
    else:
        text = text[0:10]
        return text


def replacenone(text):
    if text is None:
        return None
    else:
        text = str(text).replace(" ","")
        return text


def replaceint(text):
    if text is None:
        return None
    else:
        text = int(text)
        return text


def replaceMustint(text):
    if text is None:
        return 0
    else:
        text = int(text)
        return text


def sell_list(request):
    if request.method == "GET":
        sell_list = Sell.objects.filter(
                payment_at__isnull=False,
            ).filter(
                ~Q(order_state='결제취소'),
            ).exclude(
                # order_state = '결제취소',    
            ).values(
                'payment_at',
                'channel',
            ).annotate(
                total_amount=Sum('total_amount'),
                quantity=Sum('quantity'),
            ).annotate(
                ct=F('total_amount')/F('quantity')
            )
        print(str(sell_list.query))
        paginator = Paginator(sell_list, 20)
        page = request.GET.get('page')
        sell = paginator.get_page(page)
        return render(request, 'bflow_web/sell_list.html', {"sell": sell})
    else:
        return redirect('/sell/list')
        

def sell_create(request):
    if request.method == "POST":

        excel_file = request.FILES["excel_file"]

        wb = openpyxl.load_workbook(excel_file)

        ws = wb.active
        print(ws)

        iter_rows = iter(ws.rows)
        next(iter_rows)

        for row in iter_rows:
            product_order_number = replacenone(row[0].value)
            order_number = replacenone(row[1].value)
            payment_at = replacedate(row[2].value)
            order_state = replacenone(row[3].value)
            claim = replacenone(row[4].value)
            provide_name = replacenone(row[5].value)
            product_name = replacenone(row[6].value)
            product_option = replacenone(row[7].value)
            channel = replacenone(row[8].value)
            product_number = replacenone(row[18].value)
            product_amount = replaceint(row[19].value)
            option_amount = replaceint(row[20].value)
            seller_discount = replaceint(row[21].value)
            quantity = replaceint(row[22].value)
            total_amount = replaceint(row[23].value)
            delivery_at = replacedate(row[24].value)
            delivery_complete = replacedate(row[25].value)
            order_complete_at = replacedate(row[26].value)
            auto_complete_at = replacedate(row[27].value)
            category_number = replacenone(row[39].value)
            buyer_email = replacenone(row[40].value)
            buyer_gender = replacenone(row[41].value)
            buyer_age = replacenone(row[42].value)
            crawler = replacenone(row[43].value)
            if payment_at is not None:
                    monthStr = datetime.datetime.strptime(payment_at, '%Y-%m-%d')
                    week = monthStr.isocalendar()[1]
                    month = monthStr.month
            else:
                    week = None
                    month = None
        

            sell = Sell.objects.update_or_create(
                product_order_number = product_order_number,
                
                defaults = {
                    'order_number' : order_number,
                    'provide_name' : provide_name,
                    'product_name' : product_name,
                    'product_option' : product_option,
                    'channel' : channel,
                    'product_number' : product_number,
                    'product_amount' : product_amount,
                    'option_amount' : option_amount,
                    'seller_discount' : seller_discount,
                    'quantity' : quantity,
                    'total_amount' : total_amount,
                    'category_number' : category_number,
                    'buyer_email' : buyer_email,
                    'buyer_gender' : buyer_gender,
                    'buyer_age' : buyer_age,
                    'crawler' : crawler,
                    'order_state':order_state,
                    'claim' : claim,
                    'payment_at' : payment_at,
                    'delivery_at' : delivery_at,
                    'delivery_complete' : delivery_complete,
                    'order_complete_at' : order_complete_at,
                    'auto_complete_at' : auto_complete_at,
                    'week' : week,
                    'month' : month,
                },
            )
        msg = f'{excel_file} : 업데이트 완료'

        return render(request, 'bflow_web/sell_list.html', {"msg": msg})
    else:
        return redirect('/sell/list')

def calculate_list(request):
    if request.method == "GET":
        sell_list = Sell.objects.filter(
                payment_at__isnull=False,
            ).filter(
                ~Q(order_state='결제취소'),
            ).exclude(
                # order_state = '결제취소',    
            ).values(
                'payment_at',
                'channel',
            ).annotate(
                total_amount=Sum('total_amount'),
                quantity=Sum('quantity'),
            ).annotate(
                ct=F('total_amount')/F('quantity')
            )
        print(str(sell_list.query))
        paginator = Paginator(sell_list, 20)
        page = request.GET.get('page')
        sell = paginator.get_page(page)
        return render(request, 'bflow_web/calculate_list.html', {"sell": sell})
    else:
        return redirect('/sell/list')        

def calculate_create(request):
    if request.method == "POST":

        excel_file = request.FILES["excel_file"]

        wb = openpyxl.load_workbook(excel_file)

        ws = wb.active
        print(ws)

        iter_rows = iter(ws.rows)
        next(iter_rows)

        for row in iter_rows:

            product_order_number = replacenone(row[0].value)
            order_number = replacenone(row[1].value)
            channel_order_number = replacenone(row[2].value)
            provide_name = replacenone(row[5].value)
            channel = replacenone(row[6].value)
            quantity = replaceint(row[7].value)
            order_amount = replaceint(row[8].value)
            fees = float(row[9].value)
            order_state = replacenone(row[3].value)
            delivery_complete_at= replacedate(row[4].value)
            calculate= replaceMustint(row[10].value)
            channel_calculate= replaceMustint(row[11].value)
            complete_at= replacedate(row[12].value)
            matching_at= replacedate(row[13].value)
            monthStr = datetime.datetime.strptime(complete_at, '%Y-%m-%d')
            week = monthStr.isocalendar()[1]
            month = monthStr.month
            margin = channel_calculate - calculate


            obj, calculate = Calculate.objects.update_or_create(
                product_order_number = product_order_number,
                
                defaults = {
                    'order_number' : order_number,
                    'channel_order_number' : channel_order_number,
                    'provide_name' : provide_name,
                    'channel' : channel,
                    'quantity' : quantity,
                    'order_amount' : order_amount,
                    'fees' : fees,
                    'order_state': order_state,
                    'delivery_complete_at': delivery_complete_at,
                    'calculate': calculate,
                    'channel_calculate': channel_calculate,
                    'complete_at': complete_at,
                    'matching_at': matching_at,
                    'week' : week,
                    'month' : month,
                    'margin': margin,
                },
            )
        
        msg = f'{excel_file} : 업데이트 완료'

        return render(request, 'bflow_web/calculate_list.html', {"msg": msg})
    else:
        return redirect('/calculate/list')



# Create your views here.

bflow_app/bflow_web/templates/bflow_web/calculate_list.html
 {% extends 'bflow_web/index.html' %}
 {% block content %}
    <body style="margin-top: 30px;margin-left: 30px;">
        

        <form action="{% url "bflow_web:calculate_create" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>
        {{ msg }}
        <p></p>
        <hr>

        {% for row in excel_data %}
                {{ row }}
            <br>
        {% endfor %}
    </body>
{% endblock %}

bflow_app/bflow_web/templates/bflow_web/index.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>


<div>
        <ul>
            <li><a href="/sell/list">sell data</a></li>
            <li><a href="/calculate/list">calculate data</a></li>
            <li></li>
            <li></li>
        </ul>
</div>

<div>
    {% block content %}
    {% endblock %}
</div>

</html>

bflow_app/bflow_web/templates/bflow_web/sell_create.html
<html>
    <head>
        <title>
            Excel file upload and processing : Django Example : ThePythonDjango.Com
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "bflow_web:sell_create" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>
        
        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    </body>
</html>

bflow_app/bflow_web/templates/bflow_web/sell_list.html
{% extends 'bflow_web/index.html' %}
    {% block content %}
     <body style="margin-top: 30px;margin-left: 30px;">
        <form action="{% url "bflow_web:sell_create" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>
        {{ msg }}
        <p></p>
        <hr>
        {% for row in sell %}
            <div>
                <p>{{ row.payment_at }}</P>
                <p>{{ row.channel }}</P>
                <p>{{ row.quantity }}</P>
                <p>{{ row.total_amount }}</P>
                <p>{{ row.ct }}</P>
            </div>
            <br>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if sell.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ sell.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ sell.number }} of {{ sell.paginator.num_pages }}.
                </span>

                {% if sell.has_next %}
                    <a href="?page={{ sell.next_page_number }}">next</a>
                    <a href="?page={{ sell.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>

    {% endblock %}